fileConfigurations:
# util/lang
- source: project/util/lang/build.gradle.kts.peb
  destination: 'module/util/lang/build.gradle.kts'
- source: project/util/lang/module-info.java.peb
  destination: 'module/util/lang/src/main/java/module-info.java'
- source: project/util/lang/CollectionUtils.java.peb
  destination: 'module/util/lang/src/main/java/com/xenoterracide/{{ project }}/util/lang/CollectionUtils.java'
- source: project/util/lang/ObjectUtils.java.peb
  destination: 'module/util/lang/src/main/java/com/xenoterracide/{{ project }}/util/lang/ObjectUtils.java'
# util/test
- source: project/util/test/build.gradle.kts.peb
  destination: 'module/util/test/build.gradle.kts'
- source: project/util/test/module-info.java.peb
  destination: 'module/util/test/module-info.java'
- source: project/util/test/TestApplication.java.peb
  destination: 'module/util/test/src/test/java/com/xenoterracide/{{ project }}/TestApplication.java'
